# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: KOR

# Site title
title: "CHOI JUNYONG"

# A description of your site for meta tag, search engine results.
description: "단국대학교 도시계획부동산학부에서 도시 빅데이터, 인공지능, 도시 이동을 연구하고 가르치고 있습니다."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://mobilescape.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Research
    url: /research/
  - text: Publications
    url: https://scholar.google.com/citations?hl=ko&user=Cd3liPIAAAAJ  
  - text: Teaching
    url: /teaching/
  - text: Tags
    url: /tags/    
  - text: News
    url: /news/
  - text: Contact
    url: https://cms.dankook.ac.kr/web/urban-real/-5
#  - text: Download
#    url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; 최준용. Theme by [JustGoodThemes](https://www.justgoodthemes.com).>
  경기도 용인시 수지구 죽전로 152 단국대학교>
  Dankook University, 152, Jukjeon-ro, Suij-gu, Yongin-si, Gyeonngi-do, Korea"
  has_social: false

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
